server:
  port: 8080

spring:
  application:
    name: refactoAi
  resources:
    static-locations: classpath:/static/, classpath:/public/


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
